server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**

        - id: post-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/posts/**

        - id: graph-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/graph/**

        - id: feed-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/feed/**

        - id: search-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/search/**

security:
  jwt:
    secret: change-me-please-change-this-secret-key-32chars

logging:
  level:
    root: INFO
    com.socialmedia: DEBUG
